### ISSUE TITLE
Sequence Diagram for Mainline Scenario

### ISSUE THREAD

**Issue by Uinyw** [Uinyw/financetracker#33]
Mermaid: https://plugins.jetbrains.com/plugin/20146-mermaid, https://mermaid.js.org/syntax/sequenceDiagram.html

High level of abstraction

User creates Bank Account (Girokonto) and Savings Bank Account (Sparkonto)
User creates rules for bank account
User shops some products (relation to transaction, savings goal drops under savings goal rule)
Nutrition: Analytics

**Comment by kaessmTS** [comment]
#1d8a6c6c9b20acdfd8f5d05112ba18e4e910a347
solution added in this commit
